<?php

namespace Container5zM8V6g;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerajouterMarqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zEKXLuT.App\Controller\AdminController::ajouterMarque()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zEKXLuT.App\\Controller\\AdminController::ajouterMarque()'] = ($container->privates['.service_locator.zEKXLuT'] ?? $container->load('get_ServiceLocator_ZEKXLuTService'))->withContext('App\\Controller\\AdminController::ajouterMarque()', $container);
    }
}
