<?php

namespace ContainerDVIQASH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceControllerlisteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jfDXFDc.App\Controller\AnnonceController::liste()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jfDXFDc.App\\Controller\\AnnonceController::liste()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
            'marqueRepo' => ['privates', 'App\\Repository\\MarqueRepository', 'getMarqueRepositoryService', true],
            'favorisRepo' => ['privates', 'App\\Repository\\FavorisRepository', 'getFavorisRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\AnnonceRepository',
            'marqueRepo' => 'App\\Repository\\MarqueRepository',
            'favorisRepo' => 'App\\Repository\\FavorisRepository',
        ]))->withContext('App\\Controller\\AnnonceController::liste()', $container);
    }
}
