<?php

namespace ContainerDVIQASH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessagerieControllerconversationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.trbdNsP.App\Controller\MessagerieController::conversation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.trbdNsP.App\\Controller\\MessagerieController::conversation()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\MessagerieRepository', 'getMessagerieRepositoryService', true],
            'annonceRepo' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\MessagerieRepository',
            'annonceRepo' => 'App\\Repository\\AnnonceRepository',
        ]))->withContext('App\\Controller\\MessagerieController::conversation()', $container);
    }
}
