<?php

namespace ContainerDVIQASH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerprofilService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dgwlUSB.App\Controller\UserController::profil()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dgwlUSB.App\\Controller\\UserController::profil()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'annonceRepo' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
        ], [
            'userRepo' => 'App\\Repository\\UserRepository',
            'annonceRepo' => 'App\\Repository\\AnnonceRepository',
        ]))->withContext('App\\Controller\\UserController::profil()', $container);
    }
}
