<?php

namespace ContainerQQNlxW2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatsControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZFol7hu.App\Controller\StatsController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZFol7hu.App\\Controller\\StatsController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\StatsRepository', 'getStatsRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\StatsRepository',
        ]))->withContext('App\\Controller\\StatsController::index()', $container);
    }
}
