<?php

namespace ContainerXEzT2fB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllersupprimerUtilisateurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xioidcN.App\Controller\AdminController::supprimerUtilisateur()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xioidcN.App\\Controller\\AdminController::supprimerUtilisateur()'] = ($container->privates['.service_locator.xioidcN'] ?? $container->load('get_ServiceLocator_XioidcNService'))->withContext('App\\Controller\\AdminController::supprimerUtilisateur()', $container);
    }
}
