<?php

namespace ContainerVSDYFnn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavorisControllertoggleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._IIoh05.App\Controller\FavorisController::toggle()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._IIoh05.App\\Controller\\FavorisController::toggle()'] = ($container->privates['.service_locator._IIoh05'] ?? $container->load('get_ServiceLocator_IIoh05Service'))->withContext('App\\Controller\\FavorisController::toggle()', $container);
    }
}
