<?php

namespace ContainerROPqxBv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ArgumentResolver'.\DIRECTORY_SEPARATOR.'ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AnnonceController::liste' => ['privates', '.service_locator.S.QzeB4.App\\Controller\\AnnonceController::liste()', 'getAnnonceControllerlisteService', true],
            'App\\Controller\\AnnonceController::nouvelle' => ['privates', '.service_locator.S.QzeB4.App\\Controller\\AnnonceController::nouvelle()', 'getAnnonceControllernouvelleService', true],
            'App\\Controller\\AnnonceController::mesAnnonces' => ['privates', '.service_locator.w4AXElG.App\\Controller\\AnnonceController::mesAnnonces()', 'getAnnonceControllermesAnnoncesService', true],
            'App\\Controller\\AnnonceController::detail' => ['privates', '.service_locator.w4AXElG.App\\Controller\\AnnonceController::detail()', 'getAnnonceControllerdetailService', true],
            'App\\Controller\\AnnonceController::modifier' => ['privates', '.service_locator.S.QzeB4.App\\Controller\\AnnonceController::modifier()', 'getAnnonceControllermodifierService', true],
            'App\\Controller\\AnnonceController::supprimer' => ['privates', '.service_locator.w4AXElG.App\\Controller\\AnnonceController::supprimer()', 'getAnnonceControllersupprimerService', true],
            'App\\Controller\\AuthController::connexion' => ['privates', '.service_locator.Jt3EkEi.App\\Controller\\AuthController::connexion()', 'getAuthControllerconnexionService', true],
            'App\\Controller\\AuthController::inscription' => ['privates', '.service_locator.1OQIs_V.App\\Controller\\AuthController::inscription()', 'getAuthControllerinscriptionService', true],
            'App\\Controller\\mainController::homePage' => ['privates', '.service_locator.UD.qFKd.App\\Controller\\mainController::homePage()', 'getMainControllerhomePageService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AnnonceController:liste' => ['privates', '.service_locator.S.QzeB4.App\\Controller\\AnnonceController::liste()', 'getAnnonceControllerlisteService', true],
            'App\\Controller\\AnnonceController:nouvelle' => ['privates', '.service_locator.S.QzeB4.App\\Controller\\AnnonceController::nouvelle()', 'getAnnonceControllernouvelleService', true],
            'App\\Controller\\AnnonceController:mesAnnonces' => ['privates', '.service_locator.w4AXElG.App\\Controller\\AnnonceController::mesAnnonces()', 'getAnnonceControllermesAnnoncesService', true],
            'App\\Controller\\AnnonceController:detail' => ['privates', '.service_locator.w4AXElG.App\\Controller\\AnnonceController::detail()', 'getAnnonceControllerdetailService', true],
            'App\\Controller\\AnnonceController:modifier' => ['privates', '.service_locator.S.QzeB4.App\\Controller\\AnnonceController::modifier()', 'getAnnonceControllermodifierService', true],
            'App\\Controller\\AnnonceController:supprimer' => ['privates', '.service_locator.w4AXElG.App\\Controller\\AnnonceController::supprimer()', 'getAnnonceControllersupprimerService', true],
            'App\\Controller\\AuthController:connexion' => ['privates', '.service_locator.Jt3EkEi.App\\Controller\\AuthController::connexion()', 'getAuthControllerconnexionService', true],
            'App\\Controller\\AuthController:inscription' => ['privates', '.service_locator.1OQIs_V.App\\Controller\\AuthController::inscription()', 'getAuthControllerinscriptionService', true],
            'App\\Controller\\mainController:homePage' => ['privates', '.service_locator.UD.qFKd.App\\Controller\\mainController::homePage()', 'getMainControllerhomePageService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AnnonceController::liste' => '?',
            'App\\Controller\\AnnonceController::nouvelle' => '?',
            'App\\Controller\\AnnonceController::mesAnnonces' => '?',
            'App\\Controller\\AnnonceController::detail' => '?',
            'App\\Controller\\AnnonceController::modifier' => '?',
            'App\\Controller\\AnnonceController::supprimer' => '?',
            'App\\Controller\\AuthController::connexion' => '?',
            'App\\Controller\\AuthController::inscription' => '?',
            'App\\Controller\\mainController::homePage' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AnnonceController:liste' => '?',
            'App\\Controller\\AnnonceController:nouvelle' => '?',
            'App\\Controller\\AnnonceController:mesAnnonces' => '?',
            'App\\Controller\\AnnonceController:detail' => '?',
            'App\\Controller\\AnnonceController:modifier' => '?',
            'App\\Controller\\AnnonceController:supprimer' => '?',
            'App\\Controller\\AuthController:connexion' => '?',
            'App\\Controller\\AuthController:inscription' => '?',
            'App\\Controller\\mainController:homePage' => '?',
        ]));
    }
}
