<?php

namespace ContainerROPqxBv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceControllernouvelleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S.QzeB4.App\Controller\AnnonceController::nouvelle()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S.QzeB4.App\\Controller\\AnnonceController::nouvelle()'] = ($container->privates['.service_locator.S.QzeB4'] ?? $container->load('get_ServiceLocator_S_QzeB4Service'))->withContext('App\\Controller\\AnnonceController::nouvelle()', $container);
    }
}
