<?php

namespace ContainerROPqxBv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceControllersupprimerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w4AXElG.App\Controller\AnnonceController::supprimer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w4AXElG.App\\Controller\\AnnonceController::supprimer()'] = ($container->privates['.service_locator.w4AXElG'] ?? $container->load('get_ServiceLocator_W4AXElGService'))->withContext('App\\Controller\\AnnonceController::supprimer()', $container);
    }
}
