<?php

namespace ContainerROPqxBv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabaseServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\DatabaseService' shared autowired service.
     *
     * @return \App\Service\DatabaseService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'DatabaseService.php';

        return $container->privates['App\\Service\\DatabaseService'] = new \App\Service\DatabaseService($container->getEnv('DATABASE_URL'));
    }
}
