<?php

namespace ContainerROPqxBv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainControllerhomePageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UD.qFKd.App\Controller\mainController::homePage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UD.qFKd.App\\Controller\\mainController::homePage()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceRepo' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
            'marqueRepo' => ['privates', 'App\\Repository\\MarqueRepository', 'getMarqueRepositoryService', true],
        ], [
            'annonceRepo' => 'App\\Repository\\AnnonceRepository',
            'marqueRepo' => 'App\\Repository\\MarqueRepository',
        ]))->withContext('App\\Controller\\mainController::homePage()', $container);
    }
}
