<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVvkCJxu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVvkCJxu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVvkCJxu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVvkCJxu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVvkCJxu\App_KernelDevDebugContainer([
    'container.build_hash' => 'VvkCJxu',
    'container.build_id' => '8849eb36',
    'container.build_time' => 1776762923,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVvkCJxu');
