<?php

namespace ContainerSY95bYX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SrauzaZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SrauzaZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SrauzaZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'catalogRepo' => ['privates', 'App\\Repository\\CatalogueRepository', 'getCatalogueRepositoryService', true],
        ], [
            'catalogRepo' => 'App\\Repository\\CatalogueRepository',
        ]);
    }
}
