<?php

namespace ContainerSY95bYX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerreactiverAnnonceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KLkrrZg.App\Controller\AdminController::reactiverAnnonce()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KLkrrZg.App\\Controller\\AdminController::reactiverAnnonce()'] = ($container->privates['.service_locator.KLkrrZg'] ?? $container->load('get_ServiceLocator_KLkrrZgService'))->withContext('App\\Controller\\AdminController::reactiverAnnonce()', $container);
    }
}
