<?php

namespace ContainerSY95bYX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllercatalogueModelesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SrauzaZ.App\Controller\AdminController::catalogueModeles()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SrauzaZ.App\\Controller\\AdminController::catalogueModeles()'] = ($container->privates['.service_locator.SrauzaZ'] ?? $container->load('get_ServiceLocator_SrauzaZService'))->withContext('App\\Controller\\AdminController::catalogueModeles()', $container);
    }
}
