<?php

namespace ContainerSY95bYX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerannoncesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UD.qFKd.App\Controller\AdminController::annonces()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UD.qFKd.App\\Controller\\AdminController::annonces()'] = ($container->privates['.service_locator.UD.qFKd'] ?? $container->load('get_ServiceLocator_UD_QFKdService'))->withContext('App\\Controller\\AdminController::annonces()', $container);
    }
}
