<?php

namespace ContainerMoxnjX5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvisControllersupprimerModeleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Chdxzej.App\Controller\AvisController::supprimerModele()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Chdxzej.App\\Controller\\AvisController::supprimerModele()'] = ($container->privates['.service_locator.Chdxzej'] ?? $container->load('get_ServiceLocator_ChdxzejService'))->withContext('App\\Controller\\AvisController::supprimerModele()', $container);
    }
}
