<?php

namespace ContainerMoxnjX5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceControllerdetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vLTWnjA.App\Controller\AnnonceController::detail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vLTWnjA.App\\Controller\\AnnonceController::detail()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
            'favorisRepo' => ['privates', 'App\\Repository\\FavorisRepository', 'getFavorisRepositoryService', true],
            'avisRepo' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\AnnonceRepository',
            'favorisRepo' => 'App\\Repository\\FavorisRepository',
            'avisRepo' => 'App\\Repository\\AvisRepository',
        ]))->withContext('App\\Controller\\AnnonceController::detail()', $container);
    }
}
