<?php

namespace ContainerMoxnjX5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessagerieControllerenvoyerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LAz2Ccu.App\Controller\MessagerieController::envoyer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LAz2Ccu.App\\Controller\\MessagerieController::envoyer()'] = ($container->privates['.service_locator.LAz2Ccu'] ?? $container->load('get_ServiceLocator_LAz2CcuService'))->withContext('App\\Controller\\MessagerieController::envoyer()', $container);
    }
}
