<?php

namespace ContainerVfgRuqa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatsRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\StatsRepository' shared autowired service.
     *
     * @return \App\Repository\StatsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'StatsRepository.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'DatabaseService.php';

        return $container->privates['App\\Repository\\StatsRepository'] = new \App\Repository\StatsRepository(($container->privates['App\\Service\\DatabaseService'] ??= new \App\Service\DatabaseService($container->getEnv('DATABASE_URL'))));
    }
}
