<?php

namespace ContainerHIxAyg4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerinscriptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1OQIs_V.App\Controller\AuthController::inscription()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1OQIs_V.App\\Controller\\AuthController::inscription()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'db' => ['privates', 'App\\Service\\DatabaseService', 'getDatabaseServiceService', true],
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'db' => 'App\\Service\\DatabaseService',
            'hasher' => '?',
        ]))->withContext('App\\Controller\\AuthController::inscription()', $container);
    }
}
