<?php

namespace ContainerREtUFOR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IIoh05Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._IIoh05' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._IIoh05'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\FavorisRepository', 'getFavorisRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\FavorisRepository',
        ]);
    }
}
