<?php

namespace ContainerREtUFOR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvisControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6qOhX4i.App\Controller\AvisController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6qOhX4i.App\\Controller\\AvisController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
            'annonceRepo' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\AvisRepository',
            'annonceRepo' => 'App\\Repository\\AnnonceRepository',
        ]))->withContext('App\\Controller\\AvisController::index()', $container);
    }
}
