<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerROPqxBv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerROPqxBv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerROPqxBv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerROPqxBv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerROPqxBv\App_KernelDevDebugContainer([
    'container.build_hash' => 'ROPqxBv',
    'container.build_id' => 'b653b4ca',
    'container.build_time' => 1778074248,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerROPqxBv');
