<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVfgRuqa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVfgRuqa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVfgRuqa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVfgRuqa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVfgRuqa\App_KernelDevDebugContainer([
    'container.build_hash' => 'VfgRuqa',
    'container.build_id' => '6d07a8b5',
    'container.build_time' => 1778189966,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVfgRuqa');
