<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQQNlxW2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQQNlxW2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQQNlxW2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQQNlxW2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQQNlxW2\App_KernelDevDebugContainer([
    'container.build_hash' => 'QQNlxW2',
    'container.build_id' => 'ea9eb001',
    'container.build_time' => 1778237045,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQQNlxW2');
