<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'annonces' => [[], ['_controller' => 'App\\Controller\\AnnonceController::liste'], [], [['text', '/annonces']], [], [], []],
    'annonce_nouvelle' => [[], ['_controller' => 'App\\Controller\\AnnonceController::nouvelle'], [], [['text', '/annonces/nouvelle']], [], [], []],
    'mes_annonces' => [[], ['_controller' => 'App\\Controller\\AnnonceController::mesAnnonces'], [], [['text', '/mes-annonces']], [], [], []],
    'annonce_detail' => [['id'], ['_controller' => 'App\\Controller\\AnnonceController::detail'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/annonces']], [], [], []],
    'annonce_modifier' => [['id'], ['_controller' => 'App\\Controller\\AnnonceController::modifier'], ['id' => '\\d+'], [['text', '/modifier'], ['variable', '/', '\\d+', 'id', true], ['text', '/annonces']], [], [], []],
    'annonce_supprimer' => [['id'], ['_controller' => 'App\\Controller\\AnnonceController::supprimer'], ['id' => '\\d+'], [['text', '/supprimer'], ['variable', '/', '\\d+', 'id', true], ['text', '/annonces']], [], [], []],
    'connexion' => [[], ['_controller' => 'App\\Controller\\AuthController::connexion'], [], [['text', '/connexion']], [], [], []],
    'inscription' => [[], ['_controller' => 'App\\Controller\\AuthController::inscription'], [], [['text', '/inscription']], [], [], []],
    'deconnexion' => [[], ['_controller' => 'App\\Controller\\AuthController::deconnexion'], [], [['text', '/deconnexion']], [], [], []],
    'homePage' => [[], ['_controller' => 'App\\Controller\\mainController::homePage'], [], [['text', '/']], [], [], []],
    'vendreMaVoiture' => [[], ['_controller' => 'App\\Controller\\mainController::vendre_ma_voiture'], [], [['text', '/vendre-ma-voiture']], [], [], []],
    'App\Controller\AnnonceController::liste' => [[], ['_controller' => 'App\\Controller\\AnnonceController::liste'], [], [['text', '/annonces']], [], [], []],
    'App\Controller\AnnonceController::nouvelle' => [[], ['_controller' => 'App\\Controller\\AnnonceController::nouvelle'], [], [['text', '/annonces/nouvelle']], [], [], []],
    'App\Controller\AnnonceController::mesAnnonces' => [[], ['_controller' => 'App\\Controller\\AnnonceController::mesAnnonces'], [], [['text', '/mes-annonces']], [], [], []],
    'App\Controller\AnnonceController::detail' => [['id'], ['_controller' => 'App\\Controller\\AnnonceController::detail'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/annonces']], [], [], []],
    'App\Controller\AnnonceController::modifier' => [['id'], ['_controller' => 'App\\Controller\\AnnonceController::modifier'], ['id' => '\\d+'], [['text', '/modifier'], ['variable', '/', '\\d+', 'id', true], ['text', '/annonces']], [], [], []],
    'App\Controller\AnnonceController::supprimer' => [['id'], ['_controller' => 'App\\Controller\\AnnonceController::supprimer'], ['id' => '\\d+'], [['text', '/supprimer'], ['variable', '/', '\\d+', 'id', true], ['text', '/annonces']], [], [], []],
    'App\Controller\AuthController::connexion' => [[], ['_controller' => 'App\\Controller\\AuthController::connexion'], [], [['text', '/connexion']], [], [], []],
    'App\Controller\AuthController::inscription' => [[], ['_controller' => 'App\\Controller\\AuthController::inscription'], [], [['text', '/inscription']], [], [], []],
    'App\Controller\AuthController::deconnexion' => [[], ['_controller' => 'App\\Controller\\AuthController::deconnexion'], [], [['text', '/deconnexion']], [], [], []],
    'App\Controller\mainController::homePage' => [[], ['_controller' => 'App\\Controller\\mainController::homePage'], [], [['text', '/']], [], [], []],
    'App\Controller\mainController::vendre_ma_voiture' => [[], ['_controller' => 'App\\Controller\\mainController::vendre_ma_voiture'], [], [['text', '/vendre-ma-voiture']], [], [], []],
];
